/**
 * `pnpm env:sync` — generate per-app `.env` files from the canonical root `.env`.
 * `pnpm env:sync --example` — regenerate the committed `.env.example` files
 * (root + per-app) from the manifest's placeholders.
 *
 * The per-app `.env` files are GENERATED and gitignored: edit the root `.env`,
 * then re-run. This keeps one canonical value per secret instead of the same
 * Clerk key copied across four files under three different prefixes.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseDotenv } from "./dotenv";
import { appEnv, canonical, usedCanonicalKeys } from "./manifest";

// packages/env/src -> repo root
const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");

const GENERATED_NOTE = "# GENERATED by `pnpm env:sync` — do not edit.";
const ROOT_NOTE =
  "# Local dev secrets (gitignored). Edit here, then run `pnpm env:sync`.";

function write(path: string, lines: string[]): void {
  writeFileSync(path, `${lines.join("\n")}\n`);
  console.log(`  wrote ${path.replace(`${repoRoot}/`, "")}`);
}

/** Emit prefixed per-app `.env` files from the resolved root values. */
function syncFromRoot(): void {
  const rootPath = join(repoRoot, ".env");
  if (!existsSync(rootPath)) {
    console.error(
      `Missing root .env at ${rootPath}\n` +
        "Copy .env.example to .env and fill in your values, then re-run `pnpm env:sync`.",
    );
    process.exit(1);
  }
  const root = parseDotenv(readFileSync(rootPath, "utf8"));

  const missing: string[] = [];
  console.log("env:sync — writing per-app .env from root .env");
  for (const spec of Object.values(appEnv)) {
    const lines = [GENERATED_NOTE, ""];
    for (const [key, from] of Object.entries(spec.sources)) {
      const val = root[from];
      if (val === undefined) {
        // Optional/defaulted vars can be absent; required ones are flagged.
        missing.push(`${from} (needed for ${key})`);
        continue;
      }
      lines.push(`${key}=${val}`);
    }
    for (const dir of spec.dirs) {
      write(join(repoRoot, "apps", dir, ".env"), lines);
    }
  }
  if (missing.length > 0) {
    console.warn(
      `\nNote: these canonical keys were absent from the root .env (left unset):\n` +
        missing.map((m) => `  - ${m}`).join("\n"),
    );
  }
}

/** Regenerate committed `.env.example` files from manifest placeholders. */
function writeExamples(): void {
  console.log("env:sync --example — writing .env.example files");

  // Root .env.example — canonical keys with placeholders.
  const rootLines = [ROOT_NOTE, ""];
  for (const key of usedCanonicalKeys()) {
    const spec = canonical[key];
    if (!spec) continue;
    if (spec.comment) rootLines.push(`# ${spec.comment}`);
    rootLines.push(`${key}=${spec.example}`);
    rootLines.push("");
  }
  write(join(repoRoot, ".env.example"), rootLines);

  // Per-app .env.example — prefixed keys with placeholders (documents what each
  // app consumes; also what the drift check validates against).
  for (const spec of Object.values(appEnv)) {
    const lines = [
      GENERATED_NOTE,
      "# Generated from the root .env.example — run `pnpm env:sync` for real values.",
      "",
    ];
    for (const [key, from] of Object.entries(spec.sources)) {
      const c = canonical[from];
      if (!c) continue;
      if (c.comment) lines.push(`# ${c.comment}`);
      lines.push(`${key}=${c.example}`);
    }
    for (const dir of spec.dirs) {
      write(join(repoRoot, "apps", dir, ".env.example"), lines);
    }
  }
}

if (process.argv.includes("--example")) {
  writeExamples();
} else {
  syncFromRoot();
}
